[package]
name = "bytebraise"
version = "0.1.1"
authors = ["Chris Laplante <chris.laplante@agilent.com>"]
license = "MIT"
edition = "2018"

[dependencies]
anyhow = "1.0.45"
clap = "3.0.0-beta.5"
conch-parser = "0.1.1"
derive_more = "0.99.16"
derive_builder = "0.10.2"
im-rc = "15.0.0"
itertools = "0.10.1"
cow-utils = "0.1.2"
indexmap = "1.7.0"
lazy_static = "1.4.0"
maplit = "1.0.2"
nested_intervals = "0.2.2"
muncher = "0.7.0"
paste = "1.0.6"
phf = { version = "0.10.0", features = ["macros"] }
regex = { version = "1.5.4", features = ["pattern"] }
rowan = "0.14.1"
scopeguard = "1.1.0"
thiserror = "1.0.30"
pretty_assertions = "1.0.0"
unicode-segmentation = "1.8.0"

pyo3 = { version = "0.15.0", features = ["auto-initialize"], optional = true }
python-parser = { version = "0.2.0", optional = true }


[features]
default = []
python = ["python-parser", "pyo3"]

[[bin]]
name = "bytebraise-layers"
path = "src/bin/bytebraise_layers.rs"

