[package]
name = "bytebraise"
description = "Proof-of-concept experiment to see how much of BitBake can be implemented in Rust"
homepage = "https://github.com/Agilent/bytebraise"
repository = "https://github.com/Agilent/bytebraise"
version = "0.1.3"
authors = ["Chris Laplante <chris.laplante@agilent.com>"]
license = "MIT"
edition = "2021"

exclude = [ "/.idea" ]

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
conch-parser = "0.1.1"
derive_more = "0.99.17"
derive_builder = "0.12.0"
fxhash = "0.2.1"
im-rc = "15"
itertools = "0.10.5"
cow-utils = "0.1.2"
indexmap = "1"
lazy_static = "1"
maplit = "1"
nested_intervals = "0.2.2"
muncher = "0.7.0"
once_cell = "1"
paste = "1"
petgraph = "0.6.3"
phf = { version = "0.11.1", features = ["macros"] }
regex = { version = "1", features = ["pattern"] }
rowan = "0.15.11"
scopeguard = "1"
thiserror = "1"
pretty_assertions = "1"
unicode-segmentation = "1"

pyo3 = { version = "0.18.3", features = ["auto-initialize", "anyhow"], optional = true }
python-parser = { version = "0.2.0", optional = true }

v8 = "0.83.1"


[features]
default = []
python = ["python-parser", "pyo3"]
