[package]
name = "bytebraise-syntax"
version = "0.1.0"
edition = "2024"

[dependencies]
rowan = "0.16.1"
itertools = "0.14.0"
thiserror = "2"
cow-utils = "0.1.3"
nested_intervals = "0.6.0"
derive_builder = "0.20.2"

bytebraise-lexer = {path = "../bytebraise-lexer"}